adapter_output_directory: qc_reports/individual/adapter_detection
adapter_suffix: .adapters_inferred.fa
bam_nondedup_suffix: _Aligned.sortedByCoord.out.bam
bam_qc_reference: /fh/fast/greenberg_p/user/dchen2/BULKRNASEQ_FOR_YAPENG_250626HUMAN/data/reference/hg38_RefSeq.bed
bam_qc_reference_downsampled: /fh/fast/greenberg_p/user/dchen2/BULKRNASEQ_FOR_YAPENG_250626HUMAN/data/reference/hg38_RefSeq_2k_genes.bed
bam_qc_reports_directory: qc_reports/individual/bam_qc
bam_suffix: .bam
chr_stats_suffix: .chr_stats.txt
count_suffix: _ReadsPerGene.out.tab
counts_output_directory: outputs
counts_output_filename: raw_counts.tsv
cutadapt_output_directory: qc_reports/individual/cutadapt_output
cutadapt_output_suffix: .cutadapt_output.log
dedup_stats_directory: qc_reports/individual/dedup_stats
dedup_stats_suffix: .deduped_stats.txt
deduped_suffix: _PICARD_DEDUPED.bam
fastq_suffix: .fastq.gz
known_adapter_filename: /fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revised/example_inputs/known_adapters.fa
known_adapter_suffix: .adapters_stats.txt
mapped_bam_directory: data/mapped_bam
multiqc_output_directory: qc_reports/aggregated
n_cores: '10'
pipeline_start_step: qc_raw_fastq
qc_reports_directory: qc_reports/individual
r1: read1
r2: read2
raw_fastq_directory: /fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revised/example_inputs/data
raw_fastqc_directory: qc_reports/individual/raw_fastqc
read_distribution_suffix: .read_distribution.txt
reference_genome: /fh/fast/greenberg_p/user/dchen2/BULKRNASEQ_FOR_SHIHONG/data/reference_STAR
run_directory: /fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revised/example_gui_run
skip_trimming: false
strand_inference_suffix: .strand_inference.txt
trimmed_fastq_directory: data/trimmed_data
trimmed_fastqc_directory: qc_reports/individual/trimmed_fastqc
trimmed_suffix: _trimmed.fastq.gz
