# PIPELINE CONFIGURATION
pipeline_start_step: 'raw_fastq'
run_directory: '/fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revived/example_run'
# FASTQ CONFIGURATION
raw_fastq_directory: 'data/raw_data'
raw_fastqc_directory: 'qc_reports/individual/raw_fastqc'
fastq_suffix: '.fastq.gz'
r1: 'read1'
r2: 'read2'
# TRIMMING CONFIGURATION
trimmed_suffix: '.trimmed.fastq.gz'
trimmed_fastq_directory: 'data/trimmed_data'
trimmed_fastqc_directory: 'qc_reports/individual/trimmed_fastqc'
adapter_suffix: '.adapters_inferred.fa'
known_adapter_filename: '/fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revived/example_inputs/known_adapters.fa'
known_adapter_suffix: '.adapters_stats.txt'
adapter_output_directory: 'qc_reports/individual/adapter_detection'
cutadapt_output_suffix: 'qc_reports/individual/cutadapt_output.log'
cutadapt_output_directory: 'qc_reports/individual/cutadapt_output'
# MAPPING CONFIGURATION
mapped_bam_directory: 'data/mapped_bam'
bam_suffix: '.bam'
deduped_suffix: '.deduped.bam'
dedup_stats_suffix: '.deduped_stats.txt'
dedup_stats_directory: 'qc_reports/individual/dedup_stats'
reference_genome: '/fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revived/example_inputs/reference_hg38_STAR'
n_cores: '12'
# BAM QC CONFIGURATION
bam_qc_reports_directory: 'qc_reports/individual/bam_qc'
chr_stats_suffix: '.chr_stats.txt'
strand_inference_suffix: '.strand_inference.txt'
read_distribution_suffix: '.read_distribution.txt'
bam_qc_reference: '/fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revived/example_inputs/reference_hg38_QC.txt'
bam_qc_reference_downsampled: '/fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revived/example_inputs/reference_hg38_QC_downsampled.txt'
# COUNT AGGREGATION CONFIGURATION
count_suffix: '.counts.tsv'
counts_filename_delimiter: 'Aligned.sortedByCoord'
counts_output_filename: 'outputs/raw_counts.tsv'
qc_reports_directory: 'qc_reports/individual'
multiqc_output_directory: 'qc_reports/aggregated'