# PIPELINE CONFIGURATION
pipeline_start_step: 'qc_raw_fastq'
run_directory: '/fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revised/example_run'
# FASTQ CONFIGURATION
raw_fastq_directory: '/fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revised/example_inputs/data'
raw_fastqc_directory: 'qc_reports/individual/raw_fastqc'
fastq_suffix: '.fastq.gz'
r1: 'read1'
r2: 'read2'
# TRIMMING CONFIGURATION
skip_trimming: False
trimmed_suffix: '_trimmed.fastq.gz'
trimmed_fastq_directory: 'data/trimmed_data'
trimmed_fastqc_directory: 'qc_reports/individual/trimmed_fastqc'
adapter_suffix: '.adapters_inferred.fa'
known_adapter_filename: '/fh/fast/greenberg_p/user/dchen2/WILDLIFE/bulk_seq_revised/example_inputs/known_adapters.fa'
known_adapter_suffix: '.adapters_stats.txt'
adapter_output_directory: 'qc_reports/individual/adapter_detection'
cutadapt_output_suffix: '.cutadapt_output.log'
cutadapt_output_directory: 'qc_reports/individual/cutadapt_output'
# MAPPING CONFIGURATION
mapped_bam_directory: 'data/mapped_bam'
bam_nondedup_suffix: '_Aligned.sortedByCoord.out.bam'
deduped_suffix: '_PICARD_DEDUPED.bam'
dedup_stats_suffix: '.deduped_stats.txt'
dedup_stats_directory: 'qc_reports/individual/dedup_stats'
reference_genome: '/fh/fast/greenberg_p/user/dchen2/BULKRNASEQ_FOR_SHIHONG/data/reference_STAR'
n_cores: '12'
# BAM QC CONFIGURATION
bam_suffix: '.bam'
bam_qc_reports_directory: 'qc_reports/individual/bam_qc'
chr_stats_suffix: '.chr_stats.txt'
strand_inference_suffix: '.strand_inference.txt'
read_distribution_suffix: '.read_distribution.txt'
bam_qc_reference: '/fh/fast/greenberg_p/user/dchen2/BULKRNASEQ_FOR_YAPENG_250626HUMAN/data/reference/hg38_RefSeq.bed'
bam_qc_reference_downsampled: '/fh/fast/greenberg_p/user/dchen2/BULKRNASEQ_FOR_YAPENG_250626HUMAN/data/reference/hg38_RefSeq_2k_genes.bed'
# COUNT AGGREGATION CONFIGURATION
count_suffix: '_ReadsPerGene.out.tab'
counts_output_directory: 'outputs'
counts_output_filename: 'raw_counts.tsv'
qc_reports_directory: 'qc_reports/individual'
multiqc_output_directory: 'qc_reports/aggregated'